#!/bin/bash -e

[[ $# -ne 3 ]] && echo "USAGE: $(basename $0) [tool name] [tool version] [python version]" && exit 1
mkdir /opt/tools/${1}/${2}
tar xvf /opt/tools/${1}/${1}_${2}.tar.gz -C /opt/tools/${1}/${2}
export PATH="/root/.pyenv/versions/${3}/bin:$PATH"
python -m venv /opt/tools/${1}/${2}_venv
source /opt/tools/${1}/${2}_venv/bin/activate
grep -v '^$' /opt/tools/${1}/${2}/requirements.txt | while read l; do 
  pip install $l
done
deactivate
echo Environment created in /opt/tools/${1}/${2}_venv
