#!/bin/bash -e

set -o pipefail

[[ $# -ne 2 && $# -ne 3 ]] && echo "USAGE: $(basename $0) [--no-extract-tarball] tool_name tool_version python_version" && exit 1
extract_tarball="yes"
[[ $1 = "--no-extract-tarball" ]] && extract_tarball="" && shift
if [[ -n $extract_tarball ]]; then
    mkdir /opt/tools/${1}/${2}
    tar xvf /opt/tools/${1}/${1}_${2}.tar.gz -C /opt/tools/${1}/${2}
fi
python3 -m venv /opt/tools/${1}/${2}_venv
source /opt/tools/${1}/${2}_venv/bin/activate
pip3 install --upgrade pip
grep -v '^$' /opt/tools/${1}/${2}/requirements.txt | while read l; do 
  pip3 install $l
done
deactivate
echo Environment created in /opt/tools/${1}/${2}_venv

