steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=acceptance_api_jks --format='get(payload.data)' | tr '_-' '/+' | base64 -d > cluster/api.jks" ]
  - name: 'maven:3-jdk-11'
    id: 'Set version for Maven'
    entrypoint: mvn
    args: [ 'versions:set', '-DnewVersion=${TAG_NAME}' ]
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Prime Maven cache'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/pipeline5/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - name: europe-west4-docker.pkg.dev/hmf-build/gcloud-jdk-mvn:1.7.5
    id: 'Deploy artifacts to Maven repository'
    entrypoint: mvn
    timeout: 3600s
    args:
      - 'deploy'
      - '-Drelease'
      - '--batch-mode'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Update Maven cache after dependency resolution'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/pipeline5/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - name: 'europe-west4-docker.pkg.dev/hmf-build/docker-tag'
    id: 'Publish Docker image'
    dir: cluster
    args: ['europe-west4-docker.pkg.dev/hmf-build/pipeline5', '$TAG_NAME', 'Dockerfile', '--build-arg', 'VERSION=$TAG_NAME']
images:
  - europe-west4-docker.pkg.dev/hmf-build/pipeline5
logsBucket: 'gs://hmf-build-logs'
timeout: 4800s
options:
  machineType: 'E2_HIGHCPU_32'
