steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=acceptance_api_jks --format='get(payload.data)' | tr '_-' '/+' | base64 -d > cluster/api.jks" ]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=development_serviceaccount_key --format='get(payload.data)' | tr '_-' '/+' | base64 -d > cluster/google-key.json" ]
  - name: 'maven:3-jdk-11'
    id: 'Set version for Maven'
    entrypoint: mvn
    args: [ 'versions:set', '-DnewVersion=$TAG_NAME' ]
  - id: 'Maven build and deploy using cache'
    name: 'eu.gcr.io/hmf-build/maven-cache/alpine-java11'
    args: [ 'deploy -Drelease --batch-mode' ]
  - id: 'Publish Docker Image'
    dir: cluster
    name: 'eu.gcr.io/hmf-build/docker-tag'
    args: [ 'eu.gcr.io/$PROJECT_ID/pipeline5', '$TAG_NAME' ]
images:
  - eu.gcr.io/$PROJECT_ID/pipeline5
logsBucket: 'gs://hmf-build-logs'
timeout: 4800s
options:
  machineType: 'E2_HIGHCPU_8'
