steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=acceptance_api_jks --format='get(payload.data)' | tr '_-' '/+' | base64 -d > cluster/api.jks" ]
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Prime Maven cache'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/pipeline5/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - name: eu.gcr.io/hmf-build/gcloud-jdk-mvn:1.7.4-beta.3
    id: 'Build and install to Maven'
    entrypoint: mvn
    timeout: 3600s
    args:
      - 'install'
      - '-Drelease'
      - '--debug'
      - '--batch-mode'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - name: gcr.io/cloud-builders/gcloud
    id: Try to dump logs
    entrypoint: 'bash'
    args: [ '-c', "find /workspace/cluster/target -type f -iname '*dump*' | xargs cat" ]
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Update Maven cache after dependency resolution'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/pipeline5/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
logsBucket: 'gs://hmf-build-logs'
timeout: 4800s
options:
  machineType: 'N1_HIGHCPU_32'
