FROM google/cloud-sdk:alpine

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

# add a simple script that can auto-detect the appropriate JAVA_HOME value
# based on whether the JDK or only the JRE is installed
RUN { \
		echo '#!/bin/sh'; \
		echo 'set -e'; \
		echo; \
		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
	} > /usr/local/bin/docker-java-home \
	&& chmod +x /usr/local/bin/docker-java-home
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin

ENV JAVA_VERSION 8u171
ENV JAVA_ALPINE_VERSION 8.171.11-r0

RUN set -x \
	&& apk add --no-cache \
		openjdk8="$JAVA_ALPINE_VERSION" \
	&& [ "$JAVA_HOME" = "$(docker-java-home)" ]

ADD bin/bootstrap.sh bootstrap.sh
ADD src/main/resources/node-init.sh node-init.sh
ADD target/lib /usr/share/pipeline5/lib
ARG SYSTEM_JAR_FILE
ARG JAR_FILE
ADD target/lib/${SYSTEM_JAR_FILE} /usr/share/pipeline5/system.jar
ADD target/${JAR_FILE} /usr/share/pipeline5/bootstrap.jar

ENTRYPOINT ["./bootstrap.sh"]
