#!/bin/bash -x

set -o pipefail

function die() {
  exit_code=$?
  echo "Unknown failure: called command returned $exit_code"
  gsutil -m cp /data/output/run.log gs://outputBucket
  echo $exit_code > /tmp/JOB_FAILURE
  gsutil -m cp /tmp/JOB_FAILURE gs://outputBucket
  exit $exit_code
}

mdadm --create /dev/md0 --level=0 --raid-devices=4 /dev/nvme0n1 /dev/nvme0n2 /dev/nvme0n3 /dev/nvme0n4
mkfs.ext4 -F /dev/md0
mount /dev/md0 /data
mkdir /data/output
echo $(date) Starting run >>/data/output/run.log 2>&1 || die
mkdir /data/input >>/data/output/run.log 2>&1 || die
mkdir /data/resources >>/data/output/run.log 2>&1 || die
uname -a >>/data/output/run.log 2>&1 || die
echo "Running command ComplexCommand with bash: not_really_so_complex \"quoted\"" >>/data/output/run.log 2>&1 || die
not_really_so_complex "quoted" >>/data/output/run.log 2>&1 || die
(echo 0 > /tmp/JOB_SUCCESS && gsutil cp /tmp/JOB_SUCCESS gs://outputBucket) >>/data/output/run.log 2>&1 || die