#!/bin/bash -x

function die() {
  exit_code=$?
  echo "Unknown failure: called command returned $exit_code"
  gsutil -m cp /data/output/run.log gs://outputBucket
  echo $exit_code > /tmp/JOB_FAILURE
  gsutil -m cp /tmp/JOB_FAILURE gs://outputBucket
  exit $exit_code
}

uname -a >>/data/output/run.log 2>&1 || die
echo "Running command ComplexCommand with bash: not_really_so_complex \"quoted\"" >>/data/output/run.log 2>&1 || die
not_really_so_complex "quoted" >>/data/output/run.log 2>&1 || die
(echo 0 > /tmp/JOB_SUCCESS && gsutil cp /tmp/JOB_SUCCESS gs://outputBucket) >>/data/output/run.log 2>&1 || die