package com.hartwig.pipeline.datatypes;

public enum DataType {
    ALIGNED_READS,
    ALIGNED_READS_INDEX,
    WGSMETRICS,
    AMBER_SNPCHECK,
    GERMLINE_VARIANTS,
    GERMLINE_VARIANTS_SAGE,
    SOMATIC_VARIANTS_SAGE,
    STRUCTURAL_VARIANTS_GRIDSS,
    STRUCTURAL_VARIANTS_GRIPSS_RECOVERY,
    STRUCTURAL_VARIANTS_GRIPSS,
    SOMATIC_VARIANTS_PURPLE,
    STRUCTURAL_VARIANTS_PURPLE,
    PURPLE_PURITY,
    PURPLE_DRIVER_CATALOG,
    PURPLE_QC,
    CHORD_PREDICTION,
    COBALT,
    AMBER,
    LINX,
    LINX_BREAKENDS,
    LINX_DRIVER_CATALOG,
    LINX_FUSIONS,
    LINX_VIRAL_INSERTS,
    BACHELOR,
    BACHELOR_REPORTABLE_VARIANTS
}