package com.hartwig.pipeline.datatypes;

public enum DataType {
    ALIGNED_READS,
    ALIGNED_READS_INDEX,
    WGSMETRICS,
    READ_DEPTH_RATIO,
    B_ALLELE_FREQUENCY,
    AMBER_SNPCHECK,
    GERMLINE_VARIANTS,
    GERMLINE_VARIANTS_SAGE,
    SOMATIC_VARIANTS_SAGE,
    STRUCTURAL_VARIANTS_GRIDSS,
    STRUCTURAL_VARIANTS_GRIPSS_RECOVERY,
    STRUCTURAL_VARIANTS_GRIPSS,
    SOMATIC_VARIANTS_PURPLE,
    CHORD_PREDICTION,
    LINX_OUTPUT,
    STRUCTURAL_VARIANTS_PURPLE,
    BACHELOR_OUTPUT
}