# Use this to build the R dependencies for the pipeline.  It is not an automated part of image creation (to keep the imaging time
# down) but can be invoked manually when the dependencies are in need of updating.

install.packages("BiocManager", version="3.17")
install.packages("usethis")
install.packages("httr")
install.packages("roxygen2")
install.packages("rversions")
install.packages("codetools")
install.packages("devtools")
library(BiocManager)
library(devtools)

install.packages("dplyr")
install.packages("ggplot2", update = T, ask = F)
install.packages("patchwork", update = T, ask = F)
install.packages("ggh4x", update = T, ask = F)
install.packages("stringr", update = T, ask = F)

install.packages("magick", update = T, ask = F)
install.packages("VariantAnnotation", update = T, ask = F)
install.packages("cowplot", update = T, ask = F)

install.packages("argparser", update = T, ask = F)
install.packages("XML", update = T, ask = F)
install.packages("rtracklayer", update = T, ask = F)
install.packages("BSgenome", update = T, ask = F)
install.packages("BSgenome.Hsapiens.UCSC.hg19", update = T, ask = F)
install.packages("BSgenome.Hsapiens.UCSC.hg38", update = T, ask = F)
install.packages("tidyverse", update = T, ask = F)
install.packages("rlang", update = T, ask = F)
install.packages("R6", update = T, ask = F)

BiocManager::install("VariantAnnotation")
BiocManager::install("StructuralVariantAnnotation")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
BiocManager::install("BiocGenerics")
BiocManager::install("S4Vectors")
BiocManager::install("IRanges")
BiocManager::install("GenomeInfoDb")
BiocManager::install("GenomicRanges")
BiocManager::install("Biostrings")
BiocManager::install("Rsamtools")
BiocManager::install("GenomicAlignments")
BiocManager::install("Gviz")
BiocManager::install("copynumber", update = T, ask = F)

install.packages("testthat", update = T, ask = F)
install.packages("stringdist", update = T, ask = F)
install.packages("assertthat", update = T, ask = F)
